[build]
base = "dist"
publish = "dist"
command = "npm run build"
functions = "dist/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[dev]
command = "npm run dev"
port = 8888

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
